이수연/TIL/django/django_basic/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

이수연/TIL/django/django_basic/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

이수연/TIL/django/django_basic/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

이수연/TIL/django/django_basic/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# 우리만의 유저 만듦. 상속만 받아놓음
class User(AbstractUser):
    pass

이수연/TIL/django/django_basic/articles/models.py
from django.db import models

# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=10)
    context = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

이수연/TIL/django/django_basic/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# 장고의 기존 form 사용시 default로 사용하던 'auth.Form'이 아니므로 에러가 발생함
# 새로 정의한 'accounts.User'를 생성할 수 있도록 form을 재정의
# 아래 코드: 기존 'auth.Forms 에서 사용하는 UserCreationForm의 기능을
 # 모두 (meta class 포함) 가져와서 model만 우리가 정의한 모델로 ㅏㅂ꾸어줌
 # 모든 기능을 그대로 사용 가능함
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ['email', 'first_name']
        

이수연/TIL/django/django_basic/articles/forms.py
from django import forms
from .models import Articles
# models의 Articles클래스를 불러옴

# form class : model에 없는 값을 입력받고 싶을 때



# modelform class: model에 있는 값만 입력받고 싶을 때
class ArticleForm(forms.ModelForm):
    # 이 클래스를 설명하는 클래스 = Meta
    class Meta:
        model = Articles
        # 사용자의 입력을 원하는 필드 종류
        fields = '__all__' # 모델에 있는 모든 필드
        # exclude
        

이수연/TIL/django/django_basic/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' :  form,
    }
    return render(request, 'accounts/signup.html', context)



def login(request):
    # POST 일 때
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    
    # GET 또는 다른 매서드일때
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return render(request, 'articles/index.html')

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('articles:index')

def update(request):
    # update도 POST와 GET이기 때문에 두개로 나누는 구조 만듦
    if request.method == 'POST':
        form = CustomUserChangeForm(instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/update.html', context)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            # 비밀번호 변경 후 로그아웃 되지 않도록 session정보 업데이트 후 정보
            # 세션 정보를 통해 로그인 된 유저라는 것을 확인하기 때문에 세션 정보가 변경되면 로그아웃이 된다
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

이수연/TIL/django/django_basic/articles/views.py
                                            # 404 에러를 뜨게 함
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST
from .models import Articles
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Articles.objects.all()
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)


def detail(request, pk):
    article = get_object_or_404(Articles, pk=pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)



@require_http_methods(['GET', 'POST'])
def create(request):
    # 사용자의 입력 후 요청이 왔을 때
    if request.method == "POST":
        form = ArticleForm(request.POST)
        # 유효성 검사
        if form.is_valid():
            article = form.save()
            return redirect('articles:index')
        return redirect('articles:create')
    # 사용자가 처음으로 생성 페이지에 접근했을 때
    else:
        # form을 만들고
        form = ArticleForm()
    context = {
        'form' : form,
    }
    # return render
    return render(request, 'articles/create.html', context)

# @require_POST: Post만 가능하도록 만듦 / delete는 페이지가 필요 없기 때문 
@require_POST
def delete(request, pk):
    article = Articles.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')



def update(request, pk):
    article = get_object_or_404(Articles, pk=pk)
    if request.method == "POST" :
        form = ArticleForm(request.POST, instance=article) #기존에 있는 내용 포함
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)

    else:
        form = ArticleForm(instance=article)
    context = {
        'form' : form,
        'article' : article,
    }
    return render(request, 'articles/update.html', context)

이수연/TIL/django/django_basic/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>login Page</h1>
    <hr>
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="로그인">
    </form>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

이수연/TIL/django/django_basic/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>Signup Page</h1>
    <hr>
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="작성하기">
    </form>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

이수연/TIL/django/django_basic/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Update Page</h1>
                                    {% comment %} update는 pk가 필요 {% endcomment %}
    <form action="{% url 'accounts:update' article.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정하기">
    </form>
    <a href="{% url 'article:index'%}">뒤로가기</a>
{% endblock content %}

이수연/TIL/django/django_basic/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create Page</h1>
    <hr>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="작성하기">
    </form>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

이수연/TIL/django/django_basic/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>Detail Page</h1>
    <hr>
    <p>글 번호: {{ article.pk }}</p>
    <p>제목: {{ article.title }}</p>
    <p>생성 날짜: {{ article.created_at }}</p>
    <p>수정 날짜: {{ article.updated_at }}</p>
    <hr>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제하기">
    </form>
    <a href="{% url 'articles:update' article.pk %}">수정하기</a>
    <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

이수연/TIL/django/django_basic/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Index Page</h1>
    <a href={% url 'articles:create' %}>글 작성하기</a>
    <hr>
    {% if articles|length <= 0 %}
        <p>게시글을 작성해주세요.</p>
    {% endif %}

    {% for article in articles %}
        <p>글 번호: {{ article.pk }}</p>
        제목 : <a href="{% url 'articles:detail' article.pk %}">{{ article.title }} </a>
        <hr>
        {% endfor %}
{% endblock content %}

이수연/TIL/django/django_basic/articles/templates/articles/update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Update Page</h1>
                                    {% comment %} update는 pk가 필요 {% endcomment %}
    <form action="{% url 'articles:update' article.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="작성하기">
    </form>
    <a href="{% url 'articles:detail' article.pk %}">뒤로가기</a>
{% endblock content %}